config/routes.rb
Rails.application.routes.draw do
  resources :users, only: [:new, :create]
  resources :guesses, only: [:new, :create, :show, :index]
  resources :notes
  resources :weapons, only: [:show, :index]
  resources :people, only: [:show, :index]
  resources :rooms, only: [:show, :index]
  get 'foyer',to: 'rooms#index', as: 'foyer'
  get '/login', to: 'sessions#new', as: 'login'
  post '/login', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy'
  delete '/logout', to: 'sessions#destroy'


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/guess.rb
class Guess < ApplicationRecord
  belongs_to :weapon
  belongs_to :person
  belongs_to :room
  belongs_to :user

  def correct_answer
    if self.person_id == "2" && self.weapon_id == 2 && self.room_id == 2
      return true
    else
      false
    end
  end

end

app/models/note.rb
class Note < ApplicationRecord
  validates :text, presence: true
end

app/models/person.rb
class Person < ApplicationRecord
  belongs_to :room
  has_many :guesses
end

app/models/room.rb
class Room < ApplicationRecord
  has_one :person
  has_one :weapon
  has_many :guesses
end

app/models/user.rb
class User < ApplicationRecord
  has_many :guesses
  validates :username, {presence: true, uniqueness: true}

  has_secure_password


end

app/models/weapon.rb
class Weapon < ApplicationRecord
  belongs_to :room
  has_many :guesses
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :notepad_icon

  protect_from_forgery with: :null_session


  def notepad_icon
  end


end

app/controllers/guesses_controller.rb
class GuessesController < ApplicationController
  before_action :set_guess, only: [:show]

  def index
    cookies[:guesses] ||= 0
    @guesses = Guess.all
  end

  def new
    @guess = Guess.new
  end

  def show
  end

  def create
    cookies[:guesses]= cookies[:guesses].to_i + 1
    @guess = Guess.create(guess_params)
    # if !@guess.correct_answer
       redirect_to @guess
    # elsif @guess.correct_answer
    # end

  end

  private

  def set_guess
    @guess = Guess.find(params[:id])
  end

  def guess_params
    params.require(:guess).permit!
  end

end

app/controllers/notes_controller.rb
class NotesController < ApplicationController
  before_action :set_note, only: [:show, :update, :edit, :destroy]

    def index
      @notes = Note.all
    end

    def show
    end

    def new
      @note = Note.new
    end

    def create
      @note = Note.new(note_params)
      if @note.valid?
        @note.save
        redirect_to notes_path
      else
        render :new
      end
    end

    def edit
    end

    def update
      @note.update(note_params)

      redirect_to notes_path
    end

    def destroy
      @note.destroy
      redirect_to notes_path
    end

  private

  def set_note
    @note = Note.find(params[:id])
  end

  def note_params
    params.require(:note).permit!
  end

end

app/controllers/people_controller.rb
class PeopleController < ApplicationController
  before_action :set_person, only: [:show]

  def index
    @people = Person.all
  end

  def show
  end

  private

  def set_person
    @person = Person.find(params[:id])
  end

end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  before_action :set_room, only: [:show]

  def index
    @rooms = Room.all
  end

  def show
    @foyer = Room.find_by(name: "Foyer")
  end

  private

  def set_room
    @room = Room.find(params[:id])
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    user = User.find_by(username: params[:username])
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to room_path(1)
    else
      flash[:message] = 'Invalid Login'
      redirect_to login_path
    end
  end

  def destroy
    session.clear
    redirect_to login_path
    flash[:message] = "Logged Out"
  end

  private


end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show]

  def show
  end

  def new
    @user = User.new
  end

  def create
    @user= User.new(user_params)
    if @user.valid?
      @user.save
      redirect_to room_path(1)
    else
      flash[:messages] = @user.errors.full_messages
      redirect_to new_user_path
    end
  end


  private

  def user_params
    params.require(:user).permit!
  end

  def set_user
    @user = User.find(params[:id])
  end

end

app/controllers/weapons_controller.rb
class WeaponsController < ApplicationController
  before_action :set_weapon, only: [:show]

  def index
    @weapons = Weapon.all
  end

  def show
  end

  private

  def set_weapon
    @weapon = Weapon.find(params[:id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/guesses_helper.rb
module GuessesHelper
end

app/helpers/notes_helper.rb
module NotesHelper
end

app/helpers/people_helper.rb
module PeopleHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/weapons_helper.rb
module WeaponsHelper
end

app/views/notes/edit.html.erb
<div class="header">New Note:</div>
<body class="parchment notes">
<%= form_for @note do |f| %>
<%= f.text_area :text %>
<%= f.submit %>
<% end %>
<p></p>
<%= button_to "Delete", {:controller => :notes,
      :action => 'destroy', :id => @note.id}, :method => :delete %>
</body>

app/views/notes/index.html.erb
<head>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css"/>
  <style media="screen">
    .notes_links {
      font-size: 18px;
    }
  </style>
</head>
<body class="parchment">
<div class="notes">
  <div class="header">Notepad:</div>

<ul>
  <div class="notes_list">
  <% @notes.each do |note| %>
  <li><%= note.text %></li> <%= link_to "edit", edit_note_path(note.id) %>
<% end %>
</div>
</ul>

<div class="notes_links">

Write a <%= link_to "new note", new_note_url %>      ||
     Return to the <%= link_to "Foyer", rooms_path %>      ||
     Venture a <%= link_to "guess", new_guess_url %> ||
     <%= link_to "Logout", logout_path %>
</div>

</div>


</body>

app/views/notes/new.html.erb
<div class="header">New Note:</div>
<body class="parchment notes">
<%= form_for @note do |f| %>
<%= f.text_area :text %>
<%= f.submit %>
<% end %>
</body>

app/views/people/show.html.erb
<head>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css"/>
  <style media="screen">

</style>

</head>


<body class="person_bod">
  <div class="body_container">
    <img src="<%= asset_url @person.image_url %>" alt="" class="">

    <div class="box-1">
      <%= @person.note %>
      <p></p>
      What next?
      <ul>

        <li>Continue searching the <%= link_to @person.room.name, room_path(@person.room) %>?</li>
        <li>Return to the <%= link_to "Foyer", rooms_path %>?</li>
        <li>Take a <%=link_to "note", new_note_url %>?</li>
      </ul>

    </div>
    <!-- <div class="box-2">
      <%= @person %>
    </div>
    <div class="box-3">
      Continue searching the <%= link_to @person.room.name, room_path(@person.room) %>
    </div> -->

  </div>
</body>

app/views/rooms/index.html.erb
<head>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css"/>
  <style>
    .col-sm-4 img {
      width: 58%;
      margin: 2px;
    }
    body {
      background: #202020;
    }

    </style>
</head>

<body>
  <div class="container">
    <div class="row">
      <div class="col-sm-4">
      <a href="http://localhost:3000/rooms/4"><img src="https://www.kolbisneat.com/wp-content/uploads/2016/05/Clue14.jpg" alt=""></a>
      </div>
      <div class="col-sm-4">
      <a href="http://localhost:3000/rooms/3"><img src="https://www.kolbisneat.com/wp-content/uploads/2016/05/Clue21.jpg" alt=""></a>
      </div>
      <div class="col-sm-4">
      <a href="http://localhost:3000/rooms/6"><img src="https://www.kolbisneat.com/wp-content/uploads/2016/05/Clue16.jpg" alt=""></a>
      </div>
      </div>

    <div class="row">
    <div class="col-sm-4">
      <img src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTTQMabh5JnGfzuLH_rvm_Yynv9-Fc6itpptGOvcsqdMQXXsi9u"" alt="">
    </div>
      <div class="col-sm-4">
        <a href="http://localhost:3000/rooms/1"><img src="https://www.kolbisneat.com/wp-content/uploads/2016/05/Clue18.jpg" alt=""></a>
      </div>

<div class="col-sm-4">
  <img src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTTQMabh5JnGfzuLH_rvm_Yynv9-Fc6itpptGOvcsqdMQXXsi9u" alt="">
</div>
</div>

  <div class="row">
    <div class="col-sm-4">
      <a href="http://localhost:3000/rooms/7"><img src="https://www.kolbisneat.com/wp-content/uploads/2016/05/Clue15.jpg" alt=""></a>
      </div>
      <div class="col-sm-4">
        <a href="http://localhost:3000/rooms/2"><img src="https://www.kolbisneat.com/wp-content/uploads/2016/05/Clue19.jpg" alt=""></a>
    </div>
    <div class="col-sm-4">
  <a href="http://localhost:3000/rooms/5"><img src="https://www.kolbisneat.com/wp-content/uploads/2016/05/Clue20.jpg" alt=""></a>
  </div>
</div>
  </div>
</body>

app/views/rooms/show.html.erb
<head>
  <style media="screen">
    body {
      background-color: black;
    }
  </style>
</head>

<body>
  <div class="body_container">
    <img src="<%= asset_url @room.image_url %>" alt="" class="chunk">
    <div class="container room_container">
      <div class="row">
        <div class="col-sm">
          <% if @room.name == "Hall" %>
          <% else %>
          <a href="http://localhost:3000/people/<%= @room.person.id %>"><img src="<%= @room.person.image_url %>" alt="" class="stuff filling"></a>
          <img src="<%= @room.weapon.image_url %>" alt="" class="stuff">
        </div>
        <% end %>
    </div>
          <div class="row">
            <div class="col-sm text_box">
            <h1><%= @room.name %></h1>
            <p><%= @room.note %></p>
            <% if @room.name == "Hall" %>
            <% else %>
            <p>Speak with <%=link_to @room.person.name, person_path(@room.person)  %></p>
            <% end %>
          <p> Return to the <%= link_to "Foyer", rooms_path(@foyer) %> </p>
          <p>Take a <%= link_to "note", new_note_url %></p>
            </div>
          </div>
    </div>
</div>

</body>

app/views/users/new.html.erb
<link href="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
<script src="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
<!------ Include the above in your HEAD tag ---------->

<!DOCTYPE html>
<html>
<head>
	<style media="screen">
		label {
			color: white;
		}
	</style>
	<title>Login Page</title>
   <!--Made with love by Mutiullah Samim -->

	<!--Bootsrap 4 CDN-->
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">

    <!--Fontawesome CDN-->
	<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.3.1/css/all.css" integrity="sha384-mzrmE5qonljUremFsqc01SB46JvROS7bZs3IO2EmfFsd15uHvIt+Y8vEf7N7fWAU" crossorigin="anonymous">

	<!--Custom styles-->
	<link rel="stylesheet" type="text/css" href="styles.css">
</head>
<body class="login_bod">

<div>
</div>
<div class="container">
	<div class="d-flex justify-content-center h-100">
		<div class="card">
			<div class="card-header">
				<h3>Create User</h3>



			 </div>
			<div class="card-body">
				<div class="error"> <%= flash[:message] %> </div>
        <%= form_for @user do |f| %>
        <%= f.label "Username" %><br>
        <%= f.text_field :username %>
        <%= f.label :password %><br>
        <%= f.password_field :password %>
        <%= f.label :password_confirmation %>
        <%= f.password_field :password_confirmation %><br>
        <%= f.submit %>
        <%end %>

			</div>
			<div class="card-footer">
				<div class="d-flex justify-content-center links">
					Already have an account?<a href="http://localhost:3000/login">Sign In</a>
				</div>

			</div>
		</div>
	</div>
</div>
</body>
</html>

app/views/users/show.html.erb
Guesses Remaining: <%= @guesses %>

app/views/weapons/show.html.erb
<head>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css"/>
  <style media="screen">

</style>

</head>


<body>
  <div class="parchment">


  <div class="body_container">
    <img src="<%= asset_url @weapon.image_url %>" alt="" class="">

    <div class="box-1">
      <%=@weapon.note %>
    </div>
    <div class="box-2">
      <%= @weapon %>
    </div>
    <div class="box-3">
      Continue searching the <%= link_to @weapon.room.name, room_path(@weapon.room) %>
    </div>

  </div>
    </div>
</body>